# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0004_remove_articles_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vister', models.CharField(max_length=16, verbose_name='访客')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='标题')),
                ('content', models.TextField(verbose_name='评论')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Articles')),
                ('sub_comments', models.ManyToManyField(blank=True, related_name='_comments_sub_comments_+', to='comments.Comments')),
            ],
        ),
    ]
