# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='sub_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='upper_comments',
            field=models.ManyToManyField(blank=True, related_name='_comments_upper_comments_+', to='comments.Comments'),
        ),
    ]
