# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-06 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='分类名')),
                ('difficulty', models.IntegerField(choices=[(3, '高'), (2, '中'), (1, '低')], default=2, verbose_name='难度')),
                ('important_degree', models.IntegerField(choices=[(3, '高'), (2, '中'), (1, '低')], default=2, verbose_name='重要程度')),
                ('memo', models.CharField(max_length=128, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(verbose_name='日期')),
                ('content', models.TextField(verbose_name='日报内容')),
                ('comment', models.TextField(verbose_name='评语')),
                ('status', models.IntegerField(choices=[(0, '编写'), (1, '审核'), (2, '锁定')], default=0, verbose_name='日报状态')),
                ('hours', models.FloatField(default=7.5, verbose_name='工作时间')),
                ('categories', models.ManyToManyField(related_name='my_categories', to='daily.Categories', verbose_name='日报分类')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('signature', models.CharField(blank=True, max_length=255, null=True, verbose_name='个性签名')),
                ('head_portrait', models.ImageField(default='uploads/userprofile/default_user_head.ipg', upload_to='uploads/userprofile', verbose_name='用户头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='daily',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.UserProfile', verbose_name='所属用户'),
        ),
    ]
