# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20170206_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='评语'),
        ),
    ]
