# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-10 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_auto_20170206_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daily',
            options={'ordering': ['-upload_date', 'user']},
        ),
        migrations.AlterUniqueTogether(
            name='daily',
            unique_together=set([('upload_date', 'user')]),
        ),
    ]
