# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章')),
                ('content', models.TextField(verbose_name='内容')),
                ('mod_time', models.DateField(auto_now=True, verbose_name='修改时间')),
                ('article_type', models.IntegerField(choices=[(1, '原创'), (2, '转载'), (3, '翻译')], default=1, verbose_name='文章类型')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='标签')),
                ('brief', models.CharField(blank=True, max_length=32, null=True, verbose_name='摘要')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
    ]
