# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('blog', '0002_auto_20170212_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='作者'),
            preserve_default=False,
        ),
    ]
