# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='upper_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='upper_comments',
            field=models.ForeignKey(blank=True, default=123, on_delete=django.db.models.deletion.CASCADE, related_name='lower_comments', to='blog.Comments'),
            preserve_default=False,
        ),
    ]
