# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-26 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170226_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='upper_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lower_comments', to='blog.Comments'),
        ),
    ]
