# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170226_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='remote_host',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='客户端地址'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user_agent',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='浏览器'),
        ),
    ]
