# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='模版名称')),
                ('tempfile', models.FileField(upload_to='uploads/temp', verbose_name='模版文件')),
                ('memo', models.TextField(verbose_name='备注')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='模版修改时间')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=32, verbose_name='项目名称')),
                ('profile', models.FileField(upload_to='uploads/profile', verbose_name='配置文件')),
                ('submit_time', models.DateTimeField(auto_now=True, verbose_name='提交时间')),
                ('download_file', models.FilePathField(verbose_name='文件下载')),
            ],
        ),
        migrations.CreateModel(
            name='TechContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='标题名')),
                ('level', models.IntegerField(verbose_name='标题级别')),
                ('memo', models.TextField(verbose_name='备注')),
                ('uptitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tfMaker.TechContent', verbose_name='上级标题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='属主')),
            ],
        ),
        migrations.CreateModel(
            name='TechTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='模版名称')),
                ('memo', models.TextField(verbose_name='备注')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='模版修改时间')),
                ('tech_content', models.ManyToManyField(to='tfMaker.TechContent', verbose_name='目录')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='属主')),
            ],
        ),
        migrations.AddField(
            model_name='submitfile',
            name='tech_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfMaker.TechTemplate', verbose_name='技术方案模版'),
        ),
        migrations.AddField(
            model_name='submitfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='属主'),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfMaker.TechContent', verbose_name='对应目录'),
        ),
        migrations.AddField(
            model_name='parttemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='属主'),
        ),
    ]
