# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfMaker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techcontent',
            name='uptitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='上级标题', to='tfMaker.TechContent'),
        ),
        migrations.AlterField(
            model_name='techcontent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='属主'),
        ),
    ]
