# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-31 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tfMaker', '0002_auto_20170731_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parttemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='属主'),
        ),
        migrations.AlterField(
            model_name='submitfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='属主'),
        ),
        migrations.AlterField(
            model_name='techtemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='属主'),
        ),
    ]
